/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;
import config.dbConnector;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableModel;
import myapp.UserSessions;
import myapp.deathinfoForm;
import myapp.reservationForm;
import myapp.userdash;
import net.proteanit.sql.DbUtils;
import java.time.LocalDate;
import java.time.Period;

/**
 *
 * @author User
 */
public final class userdeathinfoPage extends javax.swing.JInternalFrame {

    

    /**
     * Creates new form userPage
     */
    public userdeathinfoPage() {
        initComponents();
        
        
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
       BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
       
        
        
        
    }
    public int calculateAge(LocalDate bdate, LocalDate ddeath) {
    if (bdate == null || ddeath == null) {
        return 0;
    }

    Period period = Period.between(bdate, ddeath);
    return period.getYears();
}
    
    
    public int validateRegister (){
      int result;
   if(di_fname.getText().isEmpty() ||di_lname.getText().isEmpty()||di_age.getText().isEmpty()||di_address.getText().isEmpty() ){
    result = 0;
   }else{
   result = 1;
   }
    return result;
    }
    
    
    Color navcolor = new Color(204,204,255);
    Color headcolor = new Color(153,153,255);
    Color bodycolor = new Color(255,204,255);

    public String getDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(bdate.getDate());
        return date;

    }
  
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        pdi_label = new javax.swing.JLabel();
        add1 = new javax.swing.JPanel();
        rv_label1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        di_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        di_fname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        di_lname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        di_age = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        di_address = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(917, 606));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setMinimumSize(new java.awt.Dimension(917, 606));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(917, 606));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 26)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Person Death Info");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 280, 30));

        jPanel2.add(jPanel3);
        jPanel3.setBounds(230, 0, 470, 70);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 70));

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setMinimumSize(new java.awt.Dimension(917, 606));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 204, 255,80));
        jPanel6.setPreferredSize(new java.awt.Dimension(917, 606));
        jPanel6.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 26)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Person's Death Form");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        jPanel6.add(jLabel4);
        jLabel4.setBounds(0, 20, 780, 70);

        close1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        close1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close1.setText("x");
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
        });
        jPanel6.add(close1);
        close1.setBounds(860, 20, 20, 29);

        add.setBackground(new java.awt.Color(204, 204, 204));
        add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pdi_label.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pdi_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pdi_label.setText("Add");
        pdi_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdi_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pdi_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pdi_labelMouseExited(evt);
            }
        });
        add.add(pdi_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 20));

        jPanel6.add(add);
        add.setBounds(290, 520, 80, 40);

        add1.setBackground(new java.awt.Color(204, 204, 204));
        add1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add1MouseExited(evt);
            }
        });
        add1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rv_label1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rv_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rv_label1.setText("Back");
        rv_label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rv_label1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rv_label1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rv_label1MouseExited(evt);
            }
        });
        add1.add(rv_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 20));

        jPanel6.add(add1);
        add1.setBounds(490, 520, 80, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("ID:");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(230, 110, 23, 40);

        di_id.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        di_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        di_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        di_id.setEnabled(false);
        di_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                di_idActionPerformed(evt);
            }
        });
        jPanel6.add(di_id);
        di_id.setBounds(340, 110, 260, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("First Name:");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(230, 160, 87, 40);

        di_fname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        di_fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        di_fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.add(di_fname);
        di_fname.setBounds(340, 160, 260, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setText("Last Name:");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(230, 210, 84, 40);

        di_lname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        di_lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        di_lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.add(di_lname);
        di_lname.setBounds(340, 210, 260, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setText("Age:");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(230, 260, 33, 40);

        di_age.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        di_age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        di_age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        di_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                di_ageActionPerformed(evt);
            }
        });
        jPanel6.add(di_age);
        di_age.setBounds(340, 260, 260, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setText("Birth date:");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(220, 310, 79, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setText("Date of date:");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(220, 370, 96, 40);

        di_address.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        di_address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        di_address.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel6.add(di_address);
        di_address.setBounds(340, 410, 260, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Address");
        jPanel6.add(jLabel2);
        jLabel2.setBounds(220, 430, 60, 19);

        jLabel5.setText("This field is autogenerated");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(340, 90, 180, 20);

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 780, 610));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/There is a Hope and a Purpose Beyond the Broken Places Archives ~ Cups of Hope Cafe.jpg"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 750));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void di_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_di_idActionPerformed

    }//GEN-LAST:event_di_idActionPerformed

    private void di_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_di_ageActionPerformed

    }//GEN-LAST:event_di_ageActionPerformed

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked
       

    }//GEN-LAST:event_close1MouseClicked

    private void pdi_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdi_labelMouseClicked

        int check = validateRegister();
if (check == 1) {
    // Calculate age
    java.util.Date bdateValue = bdate.getDate();
    java.util.Date ddeathValue = ddeath.getDate();
    LocalDate birthDate = LocalDate.of(bdateValue.getYear() + 1900, bdateValue.getMonth() + 1, bdateValue.getDate());
    LocalDate deathDate = LocalDate.of(ddeathValue.getYear() + 1900, ddeathValue.getMonth() + 1, ddeathValue.getDate());
    int age = calculateAge(birthDate, deathDate);
    
    di_age.setText(String.valueOf(age));

    dbConnector dbc = new dbConnector();
    int result;
    result = dbc.insertData("INSERT INTO tbl_pdinfo (pdi_fname, pdi_lname, pdi_age, pdi_bdate, pdi_ddate, pdi_address) VALUES (?, ?, ?, ?, ?, ?)",
        new Object[] { di_fname.getText(), di_lname.getText(), di_age.getText(), bdate.getDate(), ddeath.getDate(), di_address.getText() });

    if (result == 1) {
        // Get the last inserted ID
        int pdiId = dbc.getLastInsertedId("tbl_pdinfo", "pdi_id");
        UserSessions.setDeathPersonId(pdiId);
        System.out.println("Stored Death Person ID: " + pdiId);

        JOptionPane.showMessageDialog(null, "Successfully Saved!");
    } else {
        System.out.println("Saving Data Failed!");
    }
}

    }//GEN-LAST:event_pdi_labelMouseClicked

    private void pdi_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdi_labelMouseEntered
        // TODO add your handling code here:
        pdi_label.setBackground(bodycolor);

    }//GEN-LAST:event_pdi_labelMouseEntered

    private void pdi_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdi_labelMouseExited
        // TODO add your handling code here:

        pdi_label.setBackground(navcolor);
    }//GEN-LAST:event_pdi_labelMouseExited

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked

    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(bodycolor);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited

        add.setBackground(navcolor);
    }//GEN-LAST:event_addMouseExited

    private void rv_label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rv_label1MouseClicked
        userdash field = new userdash();
                field.setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_rv_label1MouseClicked

    private void rv_label1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rv_label1MouseEntered

    }//GEN-LAST:event_rv_label1MouseEntered

    private void rv_label1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rv_label1MouseExited

    }//GEN-LAST:event_rv_label1MouseExited

    private void add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseClicked
        
    }//GEN-LAST:event_add1MouseClicked

    private void add1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseEntered
        add1.setBackground(bodycolor);
    }//GEN-LAST:event_add1MouseEntered

    private void add1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseExited
        add1.setBackground(navcolor);
    }//GEN-LAST:event_add1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel add;
    public javax.swing.JPanel add1;
    private javax.swing.JLabel close1;
    public javax.swing.JTextField di_address;
    public javax.swing.JTextField di_age;
    public javax.swing.JTextField di_fname;
    public javax.swing.JTextField di_id;
    public javax.swing.JTextField di_lname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JLabel pdi_label;
    public javax.swing.JLabel rv_label1;
    // End of variables declaration//GEN-END:variables

}