/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;
import config.dbConnector;
import static java.awt.AWTEventMulticaster.add;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableModel;
import myapp.reservationForm;
import net.proteanit.sql.DbUtils;
import config.dbConnector;
import internalPages.reservationPage;
import java.awt.Color;
import java.sql.Statement;
import javax.swing.JOptionPane;
import myapp.UserSessions;
import myapp.userdash;

/**
 *
 * @author User
 */
public final class userreservationPage extends javax.swing.JInternalFrame {
   
    

   
    /**
     * Creates new form userPage
     */
    public userreservationPage() {
        initComponents();
        
       
        
        
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
       BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
       
        
        
        
    }
    
    public String status;
     public String action;
    
  
    
    
    Color navcolor = new Color(204,204,255);
    Color headcolor = new Color(153,153,255);
    Color bodycolor = new Color(255,204,255);

    
  public int validateRegister (){
      int result;
   if(rv_address.getText().isEmpty() ||rv_amount.getText().isEmpty() ){
    result = 0;
   }else{
   result = 1;
   }
    return result;
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        add1 = new javax.swing.JPanel();
        rv_label = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rv_amount = new javax.swing.JTextField();
        rv_address = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rv_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        rv_type = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        rv_label1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(917, 606));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setMinimumSize(new java.awt.Dimension(917, 606));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(917, 606));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 26)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Location Reservation");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 330, 30));

        jPanel2.add(jPanel3);
        jPanel3.setBounds(230, 0, 470, 70);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 70));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setForeground(new java.awt.Color(153, 153, 255));
        jPanel4.setLayout(null);

        add1.setBackground(new java.awt.Color(204, 204, 204));
        add1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add1MouseExited(evt);
            }
        });
        add1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rv_label.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rv_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rv_label.setText("Add");
        rv_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rv_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rv_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rv_labelMouseExited(evt);
            }
        });
        add1.add(rv_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 30));

        jPanel4.add(add1);
        add1.setBounds(250, 510, 110, 50);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setText("Amount:");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(230, 250, 61, 40);

        rv_amount.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rv_amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rv_amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rv_amount.setOpaque(false);
        jPanel4.add(rv_amount);
        rv_amount.setBounds(300, 250, 260, 40);

        rv_address.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rv_address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rv_address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rv_address.setOpaque(false);
        jPanel4.add(rv_address);
        rv_address.setBounds(300, 190, 260, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Address:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(230, 190, 65, 40);

        rv_id.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rv_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rv_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rv_id.setEnabled(false);
        rv_id.setOpaque(false);
        jPanel4.add(rv_id);
        rv_id.setBounds(300, 140, 260, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("ID:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(230, 130, 23, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("Status:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(230, 360, 53, 40);

        male.setBackground(new java.awt.Color(255, 255, 255,80));
        male.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        male.setText("Reserve");
        male.setBorder(null);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel4.add(male);
        male.setBounds(310, 370, 110, 20);

        female.setBackground(new java.awt.Color(255, 255, 255));
        female.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        female.setText("Not reserve");
        female.setBorder(null);
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel4.add(female);
        female.setBounds(440, 370, 120, 20);

        rv_type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rv_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Land Burial", "Cement Burial" }));
        jPanel4.add(rv_type);
        rv_type.setBounds(300, 310, 260, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setText("Type:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(230, 310, 60, 40);

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 1, 26)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Location Reservation Form");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(190, 30, 430, 30);

        close.setBackground(new java.awt.Color(204, 204, 204));
        close.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rv_label1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rv_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rv_label1.setText("Back");
        rv_label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rv_label1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rv_label1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rv_label1MouseExited(evt);
            }
        });
        close.add(rv_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 30));

        jPanel4.add(close);
        close.setBounds(460, 510, 110, 50);

        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 204)));
        jPanel4.add(jLabel12);
        jLabel12.setBounds(0, 10, 790, 72);

        jLabel2.setText("This field is Autogenerated");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(300, 124, 190, 20);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -10, 770, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rv_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rv_labelMouseClicked
       int check = validateRegister();
if (check == 1) {
    dbConnector dbc = new dbConnector();
    int result;
    result = dbc.insertData("INSERT INTO tbl_rlocation (rl_address, rl_amount, rl_status, rl_type) VALUES (?, ?, ?, ?)",
        new Object[] { rv_address.getText(), rv_amount.getText(), status, rv_type.getSelectedItem() });

    if (result == 1) {
        // Get the last inserted ID
        int rlId = dbc.getLastInsertedId("tbl_rlocation", "rl_id");
        UserSessions.setReservationLocationId(rlId);
        System.out.println("Stored Reservation Location ID: " + rlId);
        

        JOptionPane.showMessageDialog(null,"Successfully Saved!");
    } else {
        System.out.println("Saving Data Failed!");
    }
}
       

    }//GEN-LAST:event_rv_labelMouseClicked

    private void rv_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rv_labelMouseEntered
        // TODO add your handling code here:
        rv_label.setBackground(bodycolor);

    }//GEN-LAST:event_rv_labelMouseEntered

    private void rv_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rv_labelMouseExited
        // TODO add your handling code here:

        rv_label.setBackground(navcolor);
    }//GEN-LAST:event_rv_labelMouseExited

    private void add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseClicked

    }//GEN-LAST:event_add1MouseClicked

    private void add1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseEntered
        rv_label.setBackground(bodycolor);
    }//GEN-LAST:event_add1MouseEntered

    private void add1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseExited

        rv_label.setBackground(navcolor);
    }//GEN-LAST:event_add1MouseExited

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        female.setSelected(false);
        if (male.isSelected()){
        
        status= "Reserved";
                        
                }else{
        status = null;
        }
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
            
         male.setSelected(false);
        if (female.isSelected()){
        
        status= "Not reserved";
                        
                }else{
        status = null;
        }
    }//GEN-LAST:event_femaleActionPerformed

    private void rv_label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rv_label1MouseClicked
        // TODO add your handling code here:
        userdash df = new userdash();
                    this.dispose();
                    df.setVisible(true);
    }//GEN-LAST:event_rv_label1MouseClicked

    private void rv_label1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rv_label1MouseEntered
        // TODO add your handling code here:
        rv_label.setBackground(bodycolor);
    }//GEN-LAST:event_rv_label1MouseEntered

    private void rv_label1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rv_label1MouseExited
        // TODO add your handling code here:
        rv_label.setBackground(navcolor);
    }//GEN-LAST:event_rv_label1MouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        int a = JOptionPane.showConfirmDialog(null,"Confirm Exit?");
        if(a == JOptionPane.YES_OPTION){
        System.exit(0);}
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setBackground(bodycolor);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited

        close.setBackground(navcolor);
    }//GEN-LAST:event_closeMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel add1;
    public javax.swing.JPanel close;
    public javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JRadioButton male;
    public javax.swing.JTextField rv_address;
    public javax.swing.JTextField rv_amount;
    public javax.swing.JTextField rv_id;
    public javax.swing.JLabel rv_label;
    public javax.swing.JLabel rv_label1;
    public javax.swing.JComboBox<String> rv_type;
    // End of variables declaration//GEN-END:variables

}